- name: Create a instance
  hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: keypair
      prompt: "What is the keypair name?"
      private: no
  vars:
    aws_tags:
      app: web
    instance_type: t2.nano
    ami_id: ami-9887c6e7
    region: us-east-1

  tasks:
    - name: Launch instance
      ec2:
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ region }}"
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 8
            delete_on_termination: true
        wait: true
        exact_count: 1
        count_tag: "{{ aws_tags }}"
        instance_tags: "{{ aws_tags }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      remote_user: centos
      wait_for_connection:
        delay: 10
        timeout: 120
      loop: "{{ ec2.instances }}"

- name: Configure instances
  hosts: launched
  user: centos
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest

    - name: install python
      yum:
        name: python3
        state: latest

    - name: update links
      file:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        state: link
      with_items:
        - { src: /usr/bin/python3, dest: /usr/bin/python }
        - { src: /usr/bin/pip3, dest: /usr/bin/pip }


